### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by hoxbro** [conda-forge/ibis-framework-feedstock#101]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The dependencies are not in sync with upstream. I'm pulling in an old version because of a "numpy<2 pin"
https://github.com/conda-forge/ibis-framework-feedstock/blob/772d5571e93e56af05777596f461c85703e894d0/recipe/meta.yaml#L42-L46

https://github.com/ibis-project/ibis/blob/5e2903e3f7dae9c5add1b01c4100b5f7fdbb600b/pyproject.toml#L47-L49

### Installed packages

```shell
Not relevant
```

### Environment info

```shell
Not relevant
```

**Comment by gforsyth** [comment]
Thanks for flagging this, @hoxbro -- I'll rebuild with updated dependencies.

**Comment by gforsyth** [comment]
Someone beat me to it, should be sorted now.
