### ISSUE TITLE
Please don't build from git 

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/ibis-framework-feedstock#18]
Would it be possible to build from a tagged tarball rather than a git URL?

**Comment by CJ-Wright** [comment]
One can use github tarballs to build.
Attn: @conda-forge/ibis-framework

**Comment by cpcloud** [comment]
Sure. Happy to accept PRs as well.

**Comment by cpcloud** [comment]
Just out of curiosity what's wrong with using git here?

**Comment by CJ-Wright** [comment]
https://conda-forge.org/docs/meta.html#build-from-tarballs-not-repos
This also breaks some of CF's automated infrastructure (specifically the autotick bot).
I'm sorry I won't be able to issue a PR in the near future for this.

**Comment by cpcloud** [comment]
Thanks! PR is up: https://github.com/conda-forge/ibis-framework-feedstock/pull/19
