### ISSUE TITLE
Cannot install on Linux

### ISSUE THREAD

**Issue by maximlt** [conda-forge/ibis-framework-feedstock#54]
The CI of holoviews failed at building the docs/website. I pinned it down to not being able to install ibis-framework on ubuntu from the conda-forge channel.

To reproduce it, I run this command on Ubuntu 18.04 with conda 4.10.3:
```bash
conda create -n testibis -c conda-forge ibis-framework
```

conda spends a lot of time trying to solve the environment, and fails silently.

**Comment by datapythonista** [comment]
Thanks for reporting @maximlt. We're aware of it, and hopefully we'll have a solution soon. You can follow updates on this issue: https://github.com/ibis-project/ibis/issues/3041 

We use mamba as a workaround, in case it's useful to know.

**Comment by cpcloud** [comment]
@maximlt If you don't need all of the ibis backends we also now have some split packages `ibis-framework-core`, `ibis-postgres`, `ibis-sqlite` etc which may have a greater chance of solving with `conda`.

Unfortunately, we can't do much more beyond that, and recommending a switch to `mamba`.
