### ISSUE TITLE
Build and Upgrade to v6.2.0 failed

### ISSUE THREAD

**Issue by rxm7706** [conda-forge/ibis-framework-feedstock#82]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Bot Succeeded but build failed and version was not upgraded on conda-forge

```
/.azure-pipelines/azure-pipelines-linux.yml (Line: 15, Col: 3): Unexpected value 'swapfile_size'
```
References
https://github.com/conda-forge/ibis-framework-feedstock/pull/81
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=774053&view=results
https://anaconda.org/conda-forge/ibis-framework/files

### Installed packages

```shell
NA
```

### Environment info

```shell
NA
```

**Comment by gforsyth** [comment]
Thanks for flagging this @rxm7706 !  I'm going to rebuild the current feedstock and see if the release works this time.

**Comment by gforsyth** [comment]
Took a few attempts but 6.2.0 is now available on conda-forge.  Thanks again @rxm7706!
