### ISSUE TITLE
ibis-framework and ibis-framework-core versions can differ

### ISSUE THREAD

**Issue by apmorton** [conda-forge/ibis-framework-feedstock#98]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

This caused https://github.com/conda-forge/vastdb-feedstock/pull/9 to fail pip check.

Not a huge issue, but somewhat unexpected that specifying `ibis-framework 9.0.0` doesn't actually give you 9.0.0 - you can get 9.1.0 because the pin exported by ibis-framework is `ibis-framework-core >=9.0.0,<10.0a0`

### Installed packages

```shell
ibis-framework 9.0.0
```

### Environment info

```shell
N/A
```

**Comment by gforsyth** [comment]
ugh, that's annoying.  Let me put in an explicit pin

**Comment by gforsyth** [comment]
Hey @apmorton -- thanks for reporting this.  I've got exact pins set up in #99 but I don't think it's worth backporting the builds to 9.0, so I guess the annoying workaround is to explicitly ask for both `ibis-framework` and `ibis-framework-core` with the same version pin.  
But from 9.1 onwards this shouldn't be possible.

**Comment by apmorton** [comment]
This should be a pretty trivial repodata patch.

I can send one if you don't have cycles: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock

**Comment by gforsyth** [comment]
That would be most welcome :pray:
